# Generated by Django 3.2.3 on 2021-07-06 11:38

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210706_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(help_text='Upload a versatile product image', upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Versatile Image',
                'verbose_name_plural': 'Versatile Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_vers',
            field=models.ManyToManyField(related_name='products', to='store.Image'),
        ),
    ]
