# Generated by Django 3.2.3 on 2021-07-07 15:05

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20210707_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                help_text="Upload a versatile product image",
                null=True,
                upload_to="images/",
                verbose_name="Image",
            ),
        ),
    ]
