# Generated by Django 3.2.3 on 2021-07-13 10:29

from django.db import migrations
import store.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload a product image', null=True, upload_to=store.models.upload_path, verbose_name='Image'),
        ),
    ]
