# Generated by Django 3.2.3 on 2021-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.PositiveIntegerField(choices=[(5, 'Mint'), (4, 'New'), (3, 'Good'), (2, 'Fair'), (1, 'Damaged')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Change product availability', verbose_name='Product availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Title'),
        ),
    ]
