# Generated by Django 3.2.3 on 2021-08-09 14:17

from django.db import migrations
import store.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210809_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='/Users/ELIAS/PycharmProjects/django-react-ecommerce/backend/media/images/default_placeholder.png', help_text='Upload a product image', upload_to=store.models.upload_path, verbose_name='Image'),
        ),
    ]
