# Generated by Django 3.2.3 on 2025-01-03 16:19

from django.db import migrations
import store.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=store.models.get_default_image, help_text='Upload a product image', upload_to=store.models.upload_path, verbose_name='Image'),
        ),
    ]
