# Generated by Django 3.2.3 on 2021-07-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_image_image'),
        ('order', '0004_auto_20210715_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='store.product'),
        ),
    ]
