# Generated by Django 3.2.3 on 2021-07-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_friend'),
        ('order', '0006_auto_20210715_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='orders_made', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
